GET http://localhost:3000/api

### 
GET http://localhost:3000/api/butterflies

### 
GET http://localhost:3000/api/butterflies/Hq4Rk_vOPMehRX2ar6LKX

###
POST http://localhost:3000/api/butterflies
content-Type: application/json

{
  "commonName": "Monarch Butterfly",
  "species": "Danaus plexippus",
  "article": "https://en.wikipedia.org/wiki/Monarch_butterfly"
}

###
POST http://localhost:3000/api/butterflies/Hq4Rk_vOPMehRX2ar6LKX/ratings
content-Type: application/json

{
  "userId": "-9aAFuyNIkpSzRMNux2BQ",
  "rating": 5
}
###
POST http://localhost:3000/api/butterflies/VJ5v4ZEQVL92XaaSl7xgD/ratings
content-Type: application/json

{
  "userId": "-9aAFuyNIkpSzRMNux2BQ",
  "rating": 3
}

### 
GET http://localhost:3000/api/users

### 
GET http://localhost:3000/api/users/-9aAFuyNIkpSzRMNux2BQ

### 
GET http://localhost:3000/api/users/-9aAFuyNIkpSzRMNux2BQ/ratings
###
POST http://localhost:3000/api/users
content-Type: application/json

{
  "username": "johndoe"
}
